#
# Module manifest for module 'NewManifest'
#
# Generated by: Paul H Cassidy
#
# Generated on: 5/31/2016
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'PSWebDriver.psm1'

# Version number of this module.
ModuleVersion = '0.3.0.1'

# ID used to uniquely identify this module
GUID = '87858ae4-1d31-4ad9-ab50-9f0f93058d56'

# Author of this module
Author = 'Paul H Cassidy'

# Company or vendor of this module
CompanyName = 'Warrior IT Services'

# Copyright statement for this module
Copyright = '(c) 2016 Paul H Cassidy. All rights reserved.'

# Description of the functionality provided by this module
Description = 'Web Testing API Exposed to Powershell Scripts'

# Minimum version of the Windows PowerShell engine required by this module
PowerShellVersion = '3.0'

# Processor architecture (None, X86, Amd64) required by this module
ProcessorArchitecture = 'None'

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = 'WebTesting'

        # A URL to the license for this module.
        LicenseUri = 'http://www.gnu.org/licenses/gpl.html'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/qawarrior/PSWebDriver.git'

        # A URL to an icon representing this module.
        # IconUri = ''

        # ReleaseNotes of this module
        # ReleaseNotes = ''

        # External dependent modules of this module
        # ExternalModuleDependencies = ''

    } # End of PSData hashtable
    
 } # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}

